version: "3"

services:
  geth:
    image: "ethereum/client-go:v1.8.22"
    restart: unless-stopped
    ports:
      - "30303:30303"
      - "30303:30303/udp"
      - "8545:8545"
    volumes:
      - ${PWD}/.ethereum:/root/.ethereum
    stop_signal: SIGINT
    stop_grace_period: 2m
    command:
      - --rpc
      - --rpcapi
      - "eth,txpool,net,web3"
      - --rpcaddr=0.0.0.0
      - --rpcvhosts=*
      # Minimum number of executable transaction slots guaranteed per account (default: 16)
      # - --txpool.accountslots=16
      # Maximum number of non-executable transaction slots for all accounts (default: 1024)
      # --txpool.globalqueue=1024
      # Maximum number of executable transaction slots for all accounts (default: 4096)
      # - --txpool.globalslots=10000
      # Maximum amount of time non-executable transaction are queued (default: 3h0m0s)
      # - --txpool.lifetime=3h0m0s
      # Megabytes of memory allocated to internal caching (default: 1024)
      # - --cache=4096
      # Maximum number of network peers (network disabled if set to 0) (default: 25)
      # - --maxpeers=100
      # Blockchain sync mode ("fast", "full", or "light")
      # - --syncmode=fast
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
